name: Playwright Smoke Tests

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1-5'  # Runs at 5:00 AM CET (3:00 AM UTC), Monday–Friday
  workflow_dispatch:

env:
  VERSION: 7.2
  TZ: Europe/Budapest
  CI: true

jobs:
  deploy_tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧩 Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: 🚀 Run tests with smoke flag
        run: npm run smoke
        env:
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PWD: ${{ secrets.ADMIN_PWD }}
          URL: ${{ vars.URL }}

      - name: 📤 Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deploy-report
          path: playwright-report/
